# Generated by Django 4.0.2 on 2022-06-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
    ]
