# Generated by Django 4.0.2 on 2022-06-07 07:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['start_time'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='My new project', max_length=1000, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project', max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Start time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Team'),
        ),
    ]
