# Generated by Django 4.0.2 on 2022-06-08 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_project_description_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Text')),
                ('start_time', models.DateTimeField(db_index=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='End time')),
                ('severity', models.IntegerField(choices=[(1, 'minor'), (2, 'medium'), (3, 'major'), (4, 'critical')], verbose_name='Severity')),
                ('status', models.IntegerField(choices=[(0, 'backlog'), (1, 'to do'), (2, 'doing'), (3, 'done')], verbose_name='Status')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Performer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
        ),
    ]
