# Generated by Django 4.0.2 on 2022-06-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_options_alter_task_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='severity',
            field=models.CharField(choices=[('1', 'minor'), ('2', 'medium'), ('3', 'major'), ('4', 'critical')], max_length=2, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'backlog'), ('1', 'to do'), ('2', 'doing'), ('3', 'done')], max_length=2, verbose_name='Status'),
        ),
    ]
