# Generated by Django 4.0.2 on 2022-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_bug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.IntegerField(choices=[(1, 'minor'), (2, 'medium'), (3, 'major'), (4, 'critical')], verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='task',
            name='severity',
            field=models.IntegerField(choices=[(1, 'minor'), (2, 'medium'), (3, 'major'), (4, 'critical')], verbose_name='Severity'),
        ),
    ]
