# Generated by Django 4.0.2 on 2022-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_bug_severity_alter_task_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='image',
        ),
        migrations.AddField(
            model_name='bug',
            name='first_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='First screenshot'),
        ),
        migrations.AddField(
            model_name='bug',
            name='second_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Second screenshot'),
        ),
        migrations.AddField(
            model_name='bug',
            name='third_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Third screenshot'),
        ),
    ]
